# 
# Synthesis run script generated by Vivado
# 

namespace eval rt {
    variable rc
}
set rt::rc [catch {
  uplevel #0 {
    set ::env(BUILTIN_SYNTH) true
    source $::env(HRT_TCL_PATH)/rtSynthPrep.tcl
    rt::HARTNDb_startJobStats
    set rt::cmdEcho 0
    rt::set_parameter writeXmsg true
    rt::set_parameter enableParallelHelperSpawn true
    set ::env(RT_TMP) "./.Xil/Vivado-5452-cod-VirtualBox/realtime/tmp"
    if { [ info exists ::env(RT_TMP) ] } {
      file mkdir $::env(RT_TMP)
    }

    rt::delete_design

    set rt::partid xczu2eg-sfva625-1-e

    set rt::multiChipSynthesisFlow false
    source $::env(SYNTH_COMMON)/common_vhdl.tcl
    set rt::defaultWorkLibName xil_defaultlib

    # Skipping read_* RTL commands because this is post-elab optimize flow
    set rt::useElabCache true
    if {$rt::useElabCache == false} {
      rt::read_verilog -sv -include /home/cod/Desktop/prj5_3/v1/prj5-dnn-harvardchen/hardware/vivado_prj/prj_5/prj_5.srcs/sources_1/bd/mpsoc/ipshared/7e3a/hdl -define USE_DDR {
      /opt/Xilinx/Vivado/2017.2/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv
      /opt/Xilinx/Vivado/2017.2/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv
    }
      rt::read_verilog -include /home/cod/Desktop/prj5_3/v1/prj5-dnn-harvardchen/hardware/vivado_prj/prj_5/prj_5.srcs/sources_1/bd/mpsoc/ipshared/7e3a/hdl -define USE_DDR {
      /home/cod/Desktop/prj5_3/v1/prj5-dnn-harvardchen/hardware/vivado_prj/prj_5/prj_5.srcs/sources_1/bd/mpsoc/ip/mpsoc_zynq_mpsoc_0/hdl/zynq_ultra_ps_e_v3_0_1.v
      /home/cod/Desktop/prj5_3/v1/prj5-dnn-harvardchen/hardware/vivado_prj/prj_5/prj_5.srcs/sources_1/bd/mpsoc/ip/mpsoc_zynq_mpsoc_0/synth/mpsoc_zynq_mpsoc_0.v
      /home/cod/Desktop/prj5_3/v1/prj5-dnn-harvardchen/hardware/vivado_prj/prj_5/prj_5.srcs/sources_1/bd/mpsoc/ipshared/f9c1/hdl/generic_baseblocks_v2_1_vl_rfs.v
      /home/cod/Desktop/prj5_3/v1/prj5-dnn-harvardchen/hardware/vivado_prj/prj_5/prj_5.srcs/sources_1/bd/mpsoc/ipshared/7e3a/hdl/axi_infrastructure_v1_1_vl_rfs.v
      /home/cod/Desktop/prj5_3/v1/prj5-dnn-harvardchen/hardware/vivado_prj/prj_5/prj_5.srcs/sources_1/bd/mpsoc/ipshared/55c0/hdl/axi_register_slice_v2_1_vl_rfs.v
      /home/cod/Desktop/prj5_3/v1/prj5-dnn-harvardchen/hardware/vivado_prj/prj_5/prj_5.srcs/sources_1/bd/mpsoc/ipshared/95b9/hdl/axi_data_fifo_v2_1_vl_rfs.v
      /home/cod/Desktop/prj5_3/v1/prj5-dnn-harvardchen/hardware/vivado_prj/prj_5/prj_5.srcs/sources_1/bd/mpsoc/ipshared/f582/hdl/axi_crossbar_v2_1_vl_rfs.v
      /home/cod/Desktop/prj5_3/v1/prj5-dnn-harvardchen/hardware/vivado_prj/prj_5/prj_5.srcs/sources_1/bd/mpsoc/ip/mpsoc_xbar_1/synth/mpsoc_xbar_1.v
      /home/cod/Desktop/prj5_3/v1/prj5-dnn-harvardchen/hardware/vivado_prj/prj_5/prj_5.srcs/sources_1/bd/mpsoc/ip/mpsoc_xbar_0/synth/mpsoc_xbar_0.v
      /home/cod/Desktop/prj5_3/v1/prj5-dnn-harvardchen/hardware/vivado_prj/prj_5/prj_5.srcs/sources_1/bd/mpsoc/ipshared/7aec/hdl/axi_mmu_v2_1_vl_rfs.v
      /home/cod/Desktop/prj5_3/v1/prj5-dnn-harvardchen/hardware/vivado_prj/prj_5/prj_5.srcs/sources_1/bd/mpsoc/ip/mpsoc_s00_mmu_0/synth/mpsoc_s00_mmu_0.v
      /home/cod/Desktop/prj5_3/v1/prj5-dnn-harvardchen/hardware/vivado_prj/prj_5/prj_5.srcs/sources_1/bd/mpsoc/ip/mpsoc_s01_mmu_0/synth/mpsoc_s01_mmu_0.v
      /home/cod/Desktop/prj5_3/v1/prj5-dnn-harvardchen/hardware/vivado_prj/prj_5/prj_5.srcs/sources_1/bd/mpsoc/ipshared/f0ae/hdl/axi_protocol_converter_v2_1_vl_rfs.v
      /home/cod/Desktop/prj5_3/v1/prj5-dnn-harvardchen/hardware/vivado_prj/prj_5/prj_5.srcs/sources_1/bd/mpsoc/ipshared/80fd/hdl/axi_clock_converter_v2_1_vl_rfs.v
      /home/cod/Desktop/prj5_3/v1/prj5-dnn-harvardchen/hardware/vivado_prj/prj_5/prj_5.srcs/sources_1/bd/mpsoc/ipshared/3bde/hdl/axi_dwidth_converter_v2_1_vlsyn_rfs.v
      /home/cod/Desktop/prj5_3/v1/prj5-dnn-harvardchen/hardware/vivado_prj/prj_5/prj_5.srcs/sources_1/bd/mpsoc/ip/mpsoc_auto_ds_2/synth/mpsoc_auto_ds_2.v
      /home/cod/Desktop/prj5_3/v1/prj5-dnn-harvardchen/hardware/vivado_prj/prj_5/prj_5.srcs/sources_1/bd/mpsoc/ip/mpsoc_auto_pc_2/synth/mpsoc_auto_pc_2.v
      /home/cod/Desktop/prj5_3/v1/prj5-dnn-harvardchen/hardware/vivado_prj/prj_5/prj_5.srcs/sources_1/bd/mpsoc/ip/mpsoc_auto_ds_1/synth/mpsoc_auto_ds_1.v
      /home/cod/Desktop/prj5_3/v1/prj5-dnn-harvardchen/hardware/vivado_prj/prj_5/prj_5.srcs/sources_1/bd/mpsoc/ip/mpsoc_auto_pc_1/synth/mpsoc_auto_pc_1.v
      /home/cod/Desktop/prj5_3/v1/prj5-dnn-harvardchen/hardware/vivado_prj/prj_5/prj_5.srcs/sources_1/bd/mpsoc/ip/mpsoc_s01_regslice_0/synth/mpsoc_s01_regslice_0.v
      /home/cod/Desktop/prj5_3/v1/prj5-dnn-harvardchen/hardware/vivado_prj/prj_5/prj_5.srcs/sources_1/bd/mpsoc/ip/mpsoc_s00_regslice_0/synth/mpsoc_s00_regslice_0.v
      /home/cod/Desktop/prj5_3/v1/prj5-dnn-harvardchen/hardware/vivado_prj/prj_5/prj_5.srcs/sources_1/bd/mpsoc/ip/mpsoc_auto_pc_3/synth/mpsoc_auto_pc_3.v
      /home/cod/Desktop/prj5_3/v1/prj5-dnn-harvardchen/hardware/vivado_prj/prj_5/prj_5.srcs/sources_1/bd/mpsoc/ip/mpsoc_auto_us_0/synth/mpsoc_auto_us_0.v
      /home/cod/Desktop/prj5_3/v1/prj5-dnn-harvardchen/hardware/vivado_prj/prj_5/prj_5.srcs/sources_1/bd/mpsoc/ip/mpsoc_auto_rs_0/synth/mpsoc_auto_rs_0.v
      /home/cod/Desktop/prj5_3/v1/prj5-dnn-harvardchen/hardware/vivado_prj/prj_5/prj_5.srcs/sources_1/bd/mpsoc/ip/mpsoc_auto_rs_w_0/synth/mpsoc_auto_rs_w_0.v
      /home/cod/Desktop/prj5_3/v1/prj5-dnn-harvardchen/hardware/vivado_prj/prj_5/prj_5.srcs/sources_1/bd/mpsoc/ip/mpsoc_auto_ds_0/synth/mpsoc_auto_ds_0.v
      /home/cod/Desktop/prj5_3/v1/prj5-dnn-harvardchen/hardware/vivado_prj/prj_5/prj_5.srcs/sources_1/bd/mpsoc/ip/mpsoc_auto_pc_0/synth/mpsoc_auto_pc_0.v
      /home/cod/Desktop/prj5_3/v1/prj5-dnn-harvardchen/hardware/vivado_prj/prj_5/prj_5.srcs/sources_1/bd/mpsoc/hdl/mpsoc.v
      /home/cod/Desktop/prj5_3/v1/prj5-dnn-harvardchen/hardware/sources/hdl/axi_lite_if.v
      /home/cod/Desktop/prj5_3/v1/prj5-dnn-harvardchen/hardware/sources/ip_catalog/mips_core/mips_cpu.v
      /home/cod/Desktop/prj5_3/v1/prj5-dnn-harvardchen/hardware/sources/hdl/mips_cpu_top.v
      /home/cod/Desktop/prj5_3/v1/prj5-dnn-harvardchen/hardware/vivado_prj/prj_5/prj_5.srcs/sources_1/imports/hdl/mpsoc_wrapper.v
      /home/cod/Desktop/prj5_3/v1/prj5-dnn-harvardchen/hardware/sources/hdl/mips_cpu_fpga.v
    }
      rt::read_vhdl -lib lib_cdc_v1_0_2 /home/cod/Desktop/prj5_3/v1/prj5-dnn-harvardchen/hardware/vivado_prj/prj_5/prj_5.srcs/sources_1/bd/mpsoc/ipshared/52cb/hdl/lib_cdc_v1_0_rfs.vhd
      rt::read_vhdl -lib proc_sys_reset_v5_0_11 /home/cod/Desktop/prj5_3/v1/prj5-dnn-harvardchen/hardware/vivado_prj/prj_5/prj_5.srcs/sources_1/bd/mpsoc/ipshared/5db7/hdl/proc_sys_reset_v5_0_vh_rfs.vhd
      rt::read_vhdl -lib xil_defaultlib {
      /home/cod/Desktop/prj5_3/v1/prj5-dnn-harvardchen/hardware/vivado_prj/prj_5/prj_5.srcs/sources_1/bd/mpsoc/ip/mpsoc_rst_zynq_mpsoc_99M_0/synth/mpsoc_rst_zynq_mpsoc_99M_0.vhd
      /home/cod/Desktop/prj5_3/v1/prj5-dnn-harvardchen/hardware/vivado_prj/prj_5/prj_5.srcs/sources_1/bd/mpsoc/ip/mpsoc_axi_uart_0/synth/mpsoc_axi_uart_0.vhd
      /home/cod/Desktop/prj5_3/v1/prj5-dnn-harvardchen/hardware/vivado_prj/prj_5/prj_5.srcs/sources_1/bd/mpsoc/ip/mpsoc_axi_gpio_0_0/synth/mpsoc_axi_gpio_0_0.vhd
      /home/cod/Desktop/prj5_3/v1/prj5-dnn-harvardchen/hardware/vivado_prj/prj_5/prj_5.srcs/sources_1/bd/mpsoc/ip/mpsoc_axi_gpio_1_0/synth/mpsoc_axi_gpio_1_0.vhd
      /home/cod/Desktop/prj5_3/v1/prj5-dnn-harvardchen/hardware/vivado_prj/prj_5/prj_5.srcs/sources_1/bd/mpsoc/ip/mpsoc_axi_gpio_2_0/synth/mpsoc_axi_gpio_2_0.vhd
      /home/cod/Desktop/prj5_3/v1/prj5-dnn-harvardchen/hardware/vivado_prj/prj_5/prj_5.srcs/sources_1/bd/mpsoc/ip/mpsoc_axi_gpio_3_0/synth/mpsoc_axi_gpio_3_0.vhd
      /home/cod/Desktop/prj5_3/v1/prj5-dnn-harvardchen/hardware/vivado_prj/prj_5/prj_5.srcs/sources_1/bd/mpsoc/ip/mpsoc_axi_gpio_4_0/synth/mpsoc_axi_gpio_4_0.vhd
      /home/cod/Desktop/prj5_3/v1/prj5-dnn-harvardchen/hardware/vivado_prj/prj_5/prj_5.srcs/sources_1/bd/mpsoc/ip/mpsoc_axi_gpio_5_0/synth/mpsoc_axi_gpio_5_0.vhd
      /home/cod/Desktop/prj5_3/v1/prj5-dnn-harvardchen/hardware/vivado_prj/prj_5/prj_5.srcs/sources_1/bd/mpsoc/ip/mpsoc_axi_gpio_6_0/synth/mpsoc_axi_gpio_6_0.vhd
      /home/cod/Desktop/prj5_3/v1/prj5-dnn-harvardchen/hardware/vivado_prj/prj_5/prj_5.srcs/sources_1/bd/mpsoc/ip/mpsoc_axi_gpio_7_0/synth/mpsoc_axi_gpio_7_0.vhd
      /home/cod/Desktop/prj5_3/v1/prj5-dnn-harvardchen/hardware/vivado_prj/prj_5/prj_5.srcs/sources_1/bd/mpsoc/ip/mpsoc_axi_gpio_dnn_0/synth/mpsoc_axi_gpio_dnn_0.vhd
    }
      rt::read_vhdl -lib axi_lite_ipif_v3_0_4 /home/cod/Desktop/prj5_3/v1/prj5-dnn-harvardchen/hardware/vivado_prj/prj_5/prj_5.srcs/sources_1/bd/mpsoc/ipshared/0ba0/hdl/axi_lite_ipif_v3_0_vh_rfs.vhd
      rt::read_vhdl -lib lib_pkg_v1_0_2 /home/cod/Desktop/prj5_3/v1/prj5-dnn-harvardchen/hardware/vivado_prj/prj_5/prj_5.srcs/sources_1/bd/mpsoc/ipshared/832a/hdl/lib_pkg_v1_0_rfs.vhd
      rt::read_vhdl -lib lib_srl_fifo_v1_0_2 /home/cod/Desktop/prj5_3/v1/prj5-dnn-harvardchen/hardware/vivado_prj/prj_5/prj_5.srcs/sources_1/bd/mpsoc/ipshared/6039/hdl/lib_srl_fifo_v1_0_rfs.vhd
      rt::read_vhdl -lib axi_uartlite_v2_0_17 /home/cod/Desktop/prj5_3/v1/prj5-dnn-harvardchen/hardware/vivado_prj/prj_5/prj_5.srcs/sources_1/bd/mpsoc/ipshared/1b8b/hdl/axi_uartlite_v2_0_vh_rfs.vhd
      rt::read_vhdl -lib interrupt_control_v3_1_4 /home/cod/Desktop/prj5_3/v1/prj5-dnn-harvardchen/hardware/vivado_prj/prj_5/prj_5.srcs/sources_1/bd/mpsoc/ipshared/e956/hdl/interrupt_control_v3_1_vh_rfs.vhd
      rt::read_vhdl -lib axi_gpio_v2_0_15 /home/cod/Desktop/prj5_3/v1/prj5-dnn-harvardchen/hardware/vivado_prj/prj_5/prj_5.srcs/sources_1/bd/mpsoc/ipshared/cb07/hdl/axi_gpio_v2_0_vh_rfs.vhd
      rt::read_vhdl -lib blk_mem_gen_v8_3_6 /home/cod/Desktop/prj5_3/v1/prj5-dnn-harvardchen/hardware/vivado_prj/prj_5/prj_5.srcs/sources_1/bd/mpsoc/ipshared/4158/hdl/blk_mem_gen_v8_3_vhsyn_rfs.vhd
      rt::read_vhdl -lib fifo_generator_v13_1_4 /home/cod/Desktop/prj5_3/v1/prj5-dnn-harvardchen/hardware/vivado_prj/prj_5/prj_5.srcs/sources_1/bd/mpsoc/ipshared/ebc2/hdl/fifo_generator_v13_1_vhsyn_rfs.vhd
      rt::read_vhdl -lib xpm /opt/Xilinx/Vivado/2017.2/data/ip/xpm/xpm_VCOMP.vhd
      rt::filesetChecksum
    }
    rt::set_parameter usePostFindUniquification true
    set rt::SDCFileList ./.Xil/Vivado-5452-cod-VirtualBox/realtime/mips_cpu_fpga_synth.xdc
    rt::sdcChecksum
    set rt::top mips_cpu_fpga
    set rt::flattenHierarchy 3
    set rt::reportTiming false
    rt::set_parameter elaborateOnly false
    rt::set_parameter elaborateRtl false
    rt::set_parameter eliminateRedundantBitOperator true
    rt::set_parameter writeBlackboxInterface true
    rt::set_parameter ramStyle auto
    rt::set_parameter merge_flipflops true
# MODE: 
    rt::set_parameter webTalkPath {/home/cod/Desktop/prj5_3/v1/prj5-dnn-harvardchen/hardware/vivado_prj/prj_5/prj_5.cache/wt}
    rt::set_parameter enableSplitFlowPath "./.Xil/Vivado-5452-cod-VirtualBox/"
    set ok_to_delete_rt_tmp true 
    if { [rt::get_parameter parallelDebug] } { 
       set ok_to_delete_rt_tmp false 
    } 
    if {$rt::useElabCache == false} {
        set oldMIITMVal [rt::get_parameter maxInputIncreaseToMerge]; rt::set_parameter maxInputIncreaseToMerge 1000
        set oldCDPCRL [rt::get_parameter createDfgPartConstrRecurLimit]; rt::set_parameter createDfgPartConstrRecurLimit 1
      rt::run_synthesis -module $rt::top
        rt::set_parameter maxInputIncreaseToMerge $oldMIITMVal
        rt::set_parameter createDfgPartConstrRecurLimit $oldCDPCRL
    }

    set rt::flowresult [ source $::env(SYNTH_COMMON)/flow.tcl ]
    rt::HARTNDb_stopJobStats
    rt::HARTNDb_reportJobStats "Synthesis Optimization Runtime"
    rt::HARTNDb_stopSystemStats
    if { $rt::flowresult == 1 } { return -code error }

    if { [ info exists ::env(RT_TMP) ] } {
      if { [info exists ok_to_delete_rt_tmp] && $ok_to_delete_rt_tmp } { 
        file delete -force $::env(RT_TMP)
      }
    }


  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] && [info exists rt::doParallel] && $rt::doParallel} { 
     $rt::db killSynthHelper $hsKey
  } 
  rt::set_parameter helper_shm_key "" 
    source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  } ; #end uplevel
} rt::result]

if { $rt::rc } {
  $rt::db resetHdlParse
  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] && [info exists rt::doParallel] && $rt::doParallel} { 
     $rt::db killSynthHelper $hsKey
  } 
  source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  return -code "error" $rt::result
}
